### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
Error 404 This icon can't be found. #8

### CODE REVIEW

**Review by NathanBnm — APPROVED** [review]

**Comment by NathanBnm** [comment]
Fixes #8

**Comment by volfpeter** [comment]
Hi,

Thanks for the pull request. I had a look at the icon and it's not quite what I had in mind. I'll think about it a bit.

Thanks!

**Comment by Fatih20** [comment]
Well, what do you have in mind then? Let me make it happen before closing the pull request out of nowhere.

**Comment by volfpeter** [comment]
Hi,
There wasn't activity since my last comment, so I've created an icon and submitted the application to AppCenter, that's why I've closed the PR.

**Pull request closed without merging**
