### PR TITLE
Improve meson integration and project structure

### LINKED ISSUE #6: Appstream validate fails
AppCenter tried to run `appstreamcli validate` on com.github.volfpeter.timer and
received the following errors:

```
W - com.github.volfpeter.timer.appdata.xml:com.github.volfpeter.timer:6
    SPDX license ID 'GPL-3.0-only' is unknown.

Validation failed: warnings: 1

```

### For more information, see:
- [The AppStream Quickstart Guide](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html)
- [The AppStream Metadata Specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html)

### Build Information
Affects Architecture: amd64
Affects Distribution: juno
Built with the following references:
- refs/tags/1.3.1

### PR DESCRIPTION
**Pull request by NathanBnm**
I improved the way your app is built with meson and improved the app structure itself to make it more consistent and clear :smile:

This PR will also fix #6 

I removed unused translation files too and split the metadata translations (`desktop` and `appdata` files)  in the `po/extra` folder from the main ones for more clarity.

I also improved the `post_install.py` script and moved it to the `meson` folder at project root.

Finally I added icon installation. But for now you don't have any icon so this is installing empty icon files. You have to create your own personal icon for your app. I'll open a issue for that.

Let me know if you have any question about this PR :wink: 

Edit: I built and installed the app and it's working fine on my side

### CODE REVIEW

**Comment by volfpeter** [comment]
@NathanBnm Whoa, thanks a lot! That's a lot of improvements.

I built the app using the getting started guide on elementary's website. As you can see, I have absolutely no experience with this technology stack, so I really appreciate your help!

**Comment by NathanBnm** [comment]
I'm not so experienced developping vala applications but I know the build system and structure quite well 😊 Happy to help.

I think the getting started guide should be a bit reviewed regarding the changes I made.

**Comment by volfpeter** [comment]
Well, thanks anyway :)

Just one more question. Is there a cookiecutter template for elementary apps somewhere? I haven't found one yet, but it would be a huge help for developers like me, who don't know the build system and project setup part, but would try their hand in application development (that I do know).

**Comment by NathanBnm** [comment]
@volfpeter you can still use https://github.com/alcadica/develop to create an app, wingpanel or switchboard template for elementary OS. However, the generated structure does not follow the best integration yet. I'm thinking to make a PR but waiting for a previous one to be merge :smile:

**Comment by volfpeter** [comment]
Thanks, I'll have a look at it. [Cookiecutter](https://cookiecutter.readthedocs.io/en/1.7.0/) is the de facto standard for this kind of templating, so it would be the best if there was a well-maintained template devs could use, but it's still better than nothing.

@NathanBnm Would you mind if I added to you the Contributing section of the readme?

**Comment by NathanBnm** [comment]
I'm gonna check that, I have never heard about Cookiecutter before.
Sure you can do that 😉

**Pull request merged**
